INSERT INTO
MOVIE_TABLE (MOVIE_UUID, MOVIE_TITLE, MOVIE_DIRECTING, MOVIE_CASTING, MOVIE_RELEASING, MOVIE_GENRE,
MOVIE_SYNOPSIS,
MOVIE_DURATION, MOVIE_AGE_RATING, POSTER_PATH, VIDEO_PATH, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, VERSION)
VALUES
(UUID(), 'Blade Runner', 'Ridley Scott', 'Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos', 1982, 'Science-fiction',
'In November 2019 Los Angeles, former police officer Rick Deckard is detained by Officer Gaff, and brought to his former supervisor, Bryant. Deckard, whose job as a "blade runner" was to track down bioengineered humanoids known as replicants and terminally "retire" them, is informed that four replicants are on Earth illegally. Deckard begins to leave, but Bryant ambiguously threatens him and Deckard stays. The two watch a video of a blade runner named Holden administering the Voight-Kampff test, which is designed to distinguish replicants from humans based on their emotional responses to questions. The test subject, Leon, shoots Holden on the second question. Bryant wants Deckard to retire Leon and three other Nexus-6 replicants: Roy Batty, Zhora, and Pris.',
113, 14, 'bladeRunner.jpg', 'bladeRunner.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),
(UUID(), 'Taxi Driver', 'Martin Scorsese', 'Robert De Niro, Jodie Foster, Albert Brooks, Harvey Keitel, Leonard Harris, Peter Boyle, Cybill Shepherd', 1976, 'Neo-noire',
'Travis Bickle is a 26-year-old honorably discharged U.S. Marine and Vietnam War veteran suffering from post-traumatic stress disorder and living alone in New York City. Travis takes a job as a night shift taxi driver to cope with his chronic insomnia and loneliness. He frequents the porn theaters on 42nd Street and keeps a diary in which he consciously attempts to include aphorisms, such as "you´re only as healthy as you feel." He is disgusted with the crime and urban decay he witnesses, and dreams about ridding "the scum off the streets". Travis becomes infatuated with Betsy, a campaign volunteer for senator and presidential candidate Charles Palantine. Travis enters the campaign office where she works, and asks her out for coffee, to which she agrees. Betsy confesses that she feels a special connection to Travis, and agrees to go on another date with him. During their date Travis takes Betsy to a porn theater, which repulses her and causes her to leave. He attempts to reconcile with her, to no avail. Enraged, he storms into the campaign office where she works, and berates her before he is ordered to leave.',
114, 16, 'taxiDriver.webp', 'taxiDriver.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),
(UUID(), 'Alien', 'Ridley Scott', 'Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton, John Hurt, Ian Holm, Yaphet Kotto', 1979, 'Horror Science-fiction',
'The commercial space tug Nostromo is returning to Earth with a seven-member crew in stasis: Captain Dallas, Executive Officer Kane, Warrant Officer Ripley, Navigator Lambert, Science Officer Ash, and engineers Parker and Brett. Detecting a transmission from a nearby moon, the ship´s computer, Mother, awakens the crew. Per company policy requiring any potential distress signal be investigated, they land on the moon despite Parker´s protests, sustaining damage from its atmosphere and rocky landscape. The engineers stay on board for repairs while Dallas, Kane, and Lambert investigate the terrain. They discover the signal originates from a derelict alien ship and enter it, losing contact with the Nostromo. Ripley deciphers part of the transmission, determining it as a warning, but cannot relay the information to those on the derelict ship.',
116, 14, 'alien.jpg', 'alien.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),
(UUID(), 'Appaloosa', 'Ed Harris', 'Viggo Mortensen, Ed Harris, Renée Zellweger, Jeremy Irons, Timothy Spall, Lance Henriksen', 2008, 'Western',
'In 1882, the small town of Appaloosa, New Mexico, is being terrorized by local rancher Randall Bragg, who killed the town´s marshal, Jack Bell, and two deputies when they came to Bragg´s ranch to arrest two men. The town hires lawman and peacekeeper Virgil Cole and his deputy Everett Hitch to protect and regain control of the town. The pair agrees on one condition: that the town follow Cole´s law and essentially cede control to him. The lawmen begin by confronting four of Bragg´s men who are causing a disturbance in the saloon. Three men refuse to allow themselves to be arrested, forcing Cole and Hitch to kill them. The fourth man surrenders and leaves the saloon. Bragg has a meeting with Cole and Hitch, initiating a standoff.',
108, 12, 'appaloosa.jpg', 'appaloosa.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),
(UUID(), 'My Neighbour Totoro', 'Hayao Miyazaki', 'Noriko Hidaka, Hitoshi Takagi, Chika Sakamoto, Sumi Shimamoto, Naoki Tatsuta', 1988, 'Anime',
'In 1950s Japan, university professor Tatsuo Kusakabe and his two daughters, Satsuki and Mei (approximately ten and four years old, respectively), move into an old house to be closer to the hospital where the girls´ mother, Yasuko, is recovering from a long-term illness. The house is inhabited by small, dark, dust-like house spirits called susuwatari which can be seen when moving from bright to dark places.[note 1] When the girls become comfortable in their new house, the susuwatari leave to find another empty house. One day, Mei discovers two small spirits who lead her into the hollow of a large camphor tree. She befriends a larger spirit, which identifies itself by a series of roars that she interprets as "Totoro". Mei thinks Totoro is the Troll from her illustrated book Three Billy Goats Gruff, with her mispronouncing Troll. She falls asleep atop Totoro, but when Satsuki finds her, she is on the ground. Despite many attempts, Mei is unable to show her family Totoro´s tree. Tatsuo comforts her by telling her that Totoro will reveal himself when he wants to.',
86, 0, 'totoro.jpg', 'totoro.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0);
