INSERT INTO
MOVIE_TABLE (MOVIE_UUID, MOVIE_TITLE, MOVIE_DIRECTING, MOVIE_CASTING, MOVIE_RELEASING, MOVIE_GENRE, MOVIE_SYNOPSIS, MOVIE_DURATION, MOVIE_AGE_RATING, POSTER_PATH, VIDEO_PATH, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, VERSION)
VALUES

(UUID(), 'Blade Runner', 'Ridley Scott', 'Harrison Ford, Sean Young, Rutger Hauer, Daryl Hannah, Edward James Olmos', 1982, 'Science-fiction',
'In November 2019 Los Angeles, former police officer Rick Deckard is detained by Officer Gaff, and brought to his former supervisor, Bryant. Deckard, whose job as a ´blade runner´ was to track down bioengineered humanoids known as replicants and terminally ´retire´ them, is informed that four replicants are on Earth illegally. Deckard begins to leave, but Bryant ambiguously threatens him and Deckard stays. The two watch a video of a blade runner named Holden administering the Voight-Kampff test, which is designed to distinguish replicants from humans based on their emotional responses to questions. The test subject, Leon, shoots Holden on the second question. Bryant wants Deckard to retire Leon and three other Nexus-6 replicants: Roy Batty, Zhora, and Pris.',
113, 14, 'bladeRunner.jpg', 'bladeRunner.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Taxi Driver', 'Martin Scorsese', 'Robert De Niro, Jodie Foster, Harvey Keitel, Peter Boyle, Cybill Shepherd', 1976, 'Neo-noire',
'Travis Bickle is a 26-year-old honorably discharged U.S. Marine and Vietnam War veteran suffering from post-traumatic stress disorder and living alone in New York City. Travis takes a job as a night shift taxi driver to cope with his chronic insomnia and loneliness. He frequents the porn theaters on 42nd Street and keeps a diary in which he consciously attempts to include aphorisms, such as ´you´re only as healthy as you feel.´ He is disgusted with the crime and urban decay he witnesses, and dreams about ridding ´the scum off the streets´. Travis becomes infatuated with Betsy, a campaign volunteer for senator and presidential candidate Charles Palantine. Travis enters the campaign office where she works, and asks her out for coffee, to which she agrees. Betsy confesses that she feels a special connection to Travis, and agrees to go on another date with him. During their date Travis takes Betsy to a porn theater, which repulses her and causes her to leave. He attempts to reconcile with her, to no avail. Enraged, he storms into the campaign office where she works, and berates her before he is ordered to leave.',
114, 16, 'taxiDriver.jpg', 'taxiDriver.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Alien', 'Ridley Scott', 'Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton, John Hurt, Ian Holm, Yaphet Kotto', 1979, 'Horror Science-fiction',
'The commercial space tug Nostromo is returning to Earth with a seven-member crew in stasis: Captain Dallas, Executive Officer Kane, Warrant Officer Ripley, Navigator Lambert, Science Officer Ash, and engineers Parker and Brett. Detecting a transmission from a nearby moon, the ship´s computer, Mother, awakens the crew. Per company policy requiring any potential distress signal be investigated, they land on the moon despite Parker´s protests, sustaining damage from its atmosphere and rocky landscape. The engineers stay on board for repairs while Dallas, Kane, and Lambert investigate the terrain. They discover the signal originates from a derelict alien ship and enter it, losing contact with the Nostromo. Ripley deciphers part of the transmission, determining it as a warning, but cannot relay the information to those on the derelict ship.',
116, 14, 'alien.jpg', 'alien.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Appaloosa', 'Ed Harris', 'Viggo Mortensen, Ed Harris, Renée Zellweger, Jeremy Irons, Ariadna Gil', 2008, 'Western',
'In 1882, the small town of Appaloosa, New Mexico, is being terrorized by local rancher Randall Bragg, who killed the town´s marshal, Jack Bell, and two deputies when they came to Bragg´s ranch to arrest two men. The town hires lawman and peacekeeper Virgil Cole and his deputy Everett Hitch to protect and regain control of the town. The pair agrees on one condition: that the town follow Cole´s law and essentially cede control to him. The lawmen begin by confronting four of Bragg´s men who are causing a disturbance in the saloon. Three men refuse to allow themselves to be arrested, forcing Cole and Hitch to kill them. The fourth man surrenders and leaves the saloon. Bragg has a meeting with Cole and Hitch, initiating a standoff.',
108, 12, 'appaloosa.jpg', 'appaloosa.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'My Neighbour Totoro', 'Hayao Miyazaki', 'voices: Noriko Hidaka, Hitoshi Takagi, Chika Sakamoto, Sumi Shimamoto, Naoki Tatsuta', 1988, 'Anime',
'In 1950s Japan, university professor Tatsuo Kusakabe and his two daughters, Satsuki and Mei (approximately ten and four years old, respectively), move into an old house to be closer to the hospital where the girls´ mother, Yasuko, is recovering from a long-term illness. The house is inhabited by small, dark, dust-like house spirits called susuwatari which can be seen when moving from bright to dark places.[note 1] When the girls become comfortable in their new house, the susuwatari leave to find another empty house. One day, Mei discovers two small spirits who lead her into the hollow of a large camphor tree. She befriends a larger spirit, which identifies itself by a series of roars that she interprets as ´Totoro´. Mei thinks Totoro is the Troll from her illustrated book Three Billy Goats Gruff, with her mispronouncing Troll. She falls asleep atop Totoro, but when Satsuki finds her, she is on the ground. Despite many attempts, Mei is unable to show her family Totoro´s tree. Tatsuo comforts her by telling her that Totoro will reveal himself when he wants to.',
86, 0, 'totoro.jpg', 'totoro.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Batman', 'Tim Burton', 'Jack Nicholson, Michael Keaton, Kim Basinger, Billy Dee Williams, Jack Palance', 1989, 'Action',
'As Gotham City approaches its bicentennial, Mayor Borg orders district attorney Harvey Dent and police Commissioner Gordon to make the city safer by incarcerating mob boss Carl Grissom. Meanwhile, reporter Alexander Knox and photojournalist Vicki Vale investigate sightings of a masked vigilante called ´Batman´ who is targeting the city´s criminals. Both attend a fundraiser hosted by billionaire industrialist Bruce Wayne, who is secretly Batman, having chosen this path after witnessing a mugger murder his parents when he was a child. During the event, Bruce becomes infatuated with Vale, but interrupts their meeting to secretly pursue Gordon when he leaves on police business.',
126, 10, 'batman.jpeg', 'batman.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Batman Returns', 'Tim Burton', 'Michael Keaton, Danny DeVito, Michelle Pfeiffer, Christopher Walken', 1992, 'Action',
'On Christmas Day, Gotham City socialites Tucker and Esther Cobblepot become the parents of a deformed baby boy, Oswald. Believing that Gotham´s high society would not welcome their baby due to his appearance and wild demeanor, the Cobblepots confine Oswald to a cage and ultimately throw him into the sewer, where he is discovered by a family of penguins underneath the Gotham Zoo.',
126, 12, 'batmanReturns.jpeg', 'batmanReturns.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Batman Begins', 'Christopher Nolan', 'Christian Bale, Michael Caine, Liam Neeson, Katie Holmes, Gary Oldman, Cillian Murphy, Tom Wilkinson, Rutger Hauer, Ken Watanabe, Morgan Freeman', 2005, 'Action',
'In Gotham City, a young Bruce Wayne falls down a dry well and is attacked by a swarm of bats, developing a fear of them. Attending the opera with his parents, Thomas and Martha, Bruce becomes frightened by performers masquerading as bats and asks to leave. Outside, mugger Joe Chill murders Bruce´s parents in front of him, and the orphaned Bruce is raised by the family butler, Alfred Pennyworth. 14 years later, Chill is paroled after testifying against mafia boss Carmine Falcone. Bruce intends to murder Chill to avenge his parents, but one of Falcone´s assassins does so first. Bruce´s childhood friend Rachel Dawes berates him for acting outside the justice system, saying that his father would be ashamed. After confronting Falcone, who tells him that real power comes from being feared, Bruce spends the next seven years traveling the world training in combat and immersing himself in the criminal underworld.',
140, 12, 'batmanBegins.jpeg', 'batmanBegins.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Joker', 'Todd Phillips', 'Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy', 2019, 'Drama',
'In 1981, party clown and aspiring stand-up comedian Arthur Fleck lives with and cares for his mother, Penny, in crime-ridden Gotham City amidst a recession. Arthur suffers from a neurological disorder that causes him to laugh uncontrollably at inappropriate times, requiring medication, for which he depends on social services. After Arthur is attacked by juvenile delinquents, his co-worker Randall gives him a revolver for self-defense. Arthur pursues a relationship with his neighbor, single mother Sophie, and invites her to see his routine at Pogo´s comedy club. At a children´s hospital, Arthur is fired when his revolver falls out of his coat in full view of the children and Randall lies to their manager the gun was Arthur´s own. Depressed on the subway, still in clown makeup, Arthur witnesses three drunk businessmen harassing a woman, and then is beaten by the group, who happen to work for Wayne Investments; he shoots and kills two of them in self-defense and murders the third as he attempts to flee. The killings are condemned by billionaire mayoral candidate Thomas Wayne, who calls his political opponents "clowns". Protesters react by donning clown masks in Arthur´s image. Budget cuts shut down the social service program, leaving Arthur without medication.',
122, 16, 'joker.jpg', 'joker.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Spider-Man', 'Sam Raimi', 'Tobey Maguire, Willem Dafoe, Kirsten Dunst, James Franco', 2002, 'Action',
'On a school trip, high school senior Peter Parker visits a Columbia University genetics laboratory with his friend Harry Osborn and his crush Mary Jane Watson. There, a genetically engineered "super-spider" bites him and he falls ill upon returning home. Meanwhile, Harry´s father Norman Osborn, a scientist and the founder and owner of Oscorp, tries to secure an important military contract. He experiments on himself with an unstable performance-enhancing chemical and goes insane, killing his assistant.',
121, 12, 'spiderman.jpg', 'spiderman.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0),

(UUID(), 'Macbeth', 'Roman Polanski', 'Jon Finch, Francesca Annis, Martin Shaw, Nicholas Selby, John Stride', 1971, 'Drama',
'In the Middle Ages, a Norwegian invasion of Scotland is suppressed by Macbeth, Thane of Glamis, and Banquo. A traitor, the Thane of Cawdor, is captured, and King Duncan decrees Macbeth shall be awarded the title of Cawdor. Macbeth and Banquo do not hear of this news; when out riding, they happen upon Three Witches, who hail Macbeth as Thane of Cawdor and future King, and Banquo as lesser and greater. At their camp, nobles arrive and inform Macbeth he has been named the Thane of Cawdor, with Macbeth simultaneously awed and frightened at the prospect of usurping Duncan, in further fulfilment of the prophecy. He writes a letter to Lady Macbeth, who is delighted at the news. However, she fears her husband has too much good nature, and vows to be cruel for him. Duncan names his eldest son, Malcolm, Prince of Cumberland, and thus heir apparent, to the displeasure of Macbeth and Malcolm´s brother Donalbain. The royal family and nobles then spend the night at Macbeth´s castle, with Lady Macbeth greeting the King and dancing with him with duplicity.',
140, 12, 'macbeth.jpg', 'macbeth.mp4', 'ADMIN', NOW(), 'ADMIN', NOW(), 0);

INSERT INTO
USER_TABLE (USER_UUID, USER_EMAIL, USER_PASSWORD, USER_ROL, USER_FIRSTNAME, USER_LASTNAME, USER_BIRTHDATE, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, VERSION)
VALUES

(UUID(), 'rick@sanchez.edu', 'F6DP3g9DFlXrfyUs7IFxCg==', 'USER', 'Rick', 'Sánchez', CURRENT_DATE, 'ADMIN', NOW(), 'ADMIN', NOW(), 0),
(UUID(), 'john@doe.com', 'F6DP3g9DFlXrfyUs7IFxCg==', 'USER', 'John', 'Doe', CURRENT_DATE, 'ADMIN', NOW(), 'ADMIN', NOW(), 0);